package helix:plugin;


interface types {
    flags requested-wasi-interfaces {
        http,
        foo,
        bar,
        baz,
        bla,
    }

    record plugin-metadata {
        name: string,
        description: string,
        keywords: list<string>,
        // TODO remove and add permissions field
        requested-wasi-interfaces: requested-wasi-interfaces,
    }

    enum log-level {
        info,
        warn,
        error,
    }

}

world editor-context {
    record rect {
        x: u16,
        y: u16,
        width: u16,
        height: u16,
    }

    resource view {
        // get-id: func() -> view-id;
        get-area: func() -> rect;
    }

    import get-focus: func() -> view;
    import remove-view: func(view: borrow<view>);
    // get-all-views: func() -> list<view>;
    import close: func();
}


world base {
    use types.{log-level, plugin-metadata};

    /// Every plugin has to provide some mandatory metadata, which may be displayed to the user.
    /// This is the only function from which a plugin may not call imported functions.
    export get-metadata: func() -> plugin-metadata;
    
    /// This function is called directly after the editor state is initialized.
    /// It allows plugins to make changes to the editor before it is rendered for the first time.
    export initialize: func();

    /// Logs some message in the helix log file.
    import log: func(level: log-level, msg: string);

    /// Logs some message in the helix log file.
    import get-text-selection: func() -> option<string>;

    // --- Basic Functions ---
    import set-editor-status: func(msg: string);
}

world keyevents {
    export handle-key-press: func(c: char);
}

// TODO It is unclear what some of these functions should return.
/// IMO not really useful for real plugin development. But there is also no reason we should disallow plugins invoking commands.
world run-typed-commands {
    /// Does option<_> make sense as a return type?
    /// Will calling quit instantly quit the editor or is the plugin allowed to continue its execution?
    /// The error should probably be returned to the plugin

    // import quit: func() -> result;
    // import quit-force: func();
    // import write-quit: func();
    // import write-quit-force: func();

    import close-buffer: func() -> result<_, string>;
}